language: rust
sudo: false

os:
 - linux
 - osx

rust:
  # TODO: pick an oldest supported release
  - stable
  - nightly

addons:
  apt:
    packages:
      - gcc-multilib

env:
  global:
    - RUSTFLAGS=--deny=warnings
    - FEATURES="push process"

script:
  - cargo test --features="$FEATURES"

matrix:
  include:
  - rust: nightly
    script:
      # Use latest clippy
      - cargo update -p clippy
      # Enable dev for clippy linting.
      - FEATURES="$FEATURES dev" cargo test --features="$FEATURES"
      # Lint nightly feature
      - FEATURES="$FEATURES dev nightly" cargo test --features="$FEATURES"

  # Test 32-bit versions. rust-prometheus only supports stable rust on 32-bit platforms.
  - rust: stable
    os: linux
    script:
      - export ARCH=i686
      - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
  - rust: stable
    os: osx
    script:
      - export ARCH=i686
      - curl -sSL https://raw.githubusercontent.com/carllerche/travis-rust-matrix/master/test | bash
